name: TheresaAnn
favicon: null
layout_spectrum: 0.7858189661055803
typography_spectrum: 0.3895873597357422
title: Strong is the New Beautiful
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.870880322996527
  lightness: 0.7011800622567534
  saturation: 0.7564864510204643
  rhythmicContrast: 0.44563790666870773
purpose: []
